name: Automatic Deployment

on:
  push:
    branches: [develop]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Welcome
        run: |
          echo Start deploying Sen Suite to ${{toJSON(github)}}
