name: Automatic Deployment

on:
  push:
    branches: [develop]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Welcome
        run: |
          echo =================================================
          echo Start deploying Sen Suite to ${{env.environment}}
          echo =================================================
